### ISSUE TITLE
Implementation of TicTacToe Multiplayer

### ISSUE THREAD

**Issue by NoWo2000** [NoWo2000/MOT-Multi-Functional-Bot#4]
If the user wants, he should be able to play the game TikTakToe with the Telegrambot.

**Comment by NoWo2000** [comment]
At the moment, it is only possible to play the TicTacToe game if you start the system locally and enter the data manually in the console, as it is not yet possible to pass on the user's input from Telegram to the programme in such a way that it can be processed properly.

**Comment by Fulachs** [comment]
Closed with #60
