### ISSUE TITLE
Sprachbarriere bei Wordle

### ISSUE THREAD

**Issue by Dornteufel1** [NoWo2000/MOT-Multi-Functional-Bot#50]
Ich würde es deutlich klarer machen, dass die Wortliste mehrsprachig ist. Der komplette Bot ist in Englisch, ich wäre nie darauf gekommen, dass mein Wort 'Hüfte' war... 
Abgesehen davon wäre eine Auflösung zum Schluss nicht schlecht.

**Comment by Fulachs** [comment]
Hi, ja das macht auch eigentlich gar keinen Sinn, dass die Wörter auf Deutsch/Englisch sind. 
Die geforderten Wörter sind mit der nächsten Version auch auf Englisch. Danke für den Tipp!

Eine Auflösung gibt es, die ist wohl nur noch etwas zu versteckt. 😅
Nach jedem Spiel steht am Ende, was das gesuchte Wort war. "Your word was ..."
![image](https://user-images.githubusercontent.com/20891899/158906980-fd513ec7-c444-4d75-8e84-1fda054c9699.png)

**Comment by Fulachs** [comment]
Die Auflösung wird nun am Ende mitgeschickt. So sollte es gut sichtbar sein.
![image](https://user-images.githubusercontent.com/20891899/158908388-3cb006ec-faec-4ed1-bb63-fde4ae27f4dc.png)

**Comment by Dornteufel1** [comment]
Vielen Dank!
